kind: role
metadata:
  description: Demo gods be with me
  name: live-demo-test-role
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    - ec2-user
    node_labels:
      'env': 'test'
  deny: {}
version: v5
