kind: role
metadata:
  description: Pipeline test role
  name: pipeline-test-role
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    - ec2-user
    node_labels:
      'env': 'test'
  deny: {}
version: v5
